### PR TITLE
Common DTOs

### PR DESCRIPTION
**Pull request by brandongregoryscott**
Partially resolves https://github.com/AndcultureCode/AndcultureCode.DotnetReact.Boilerplate/issues/11

Opted not to port the `AuditableSchemaFilter` just yet - wanted to do some refactoring and maybe add some tests around it. Can be added in a follow-up PR

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [-] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [-] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

### CODE REVIEW

**Review by jstevenson — APPROVED** [review]

**Review by myty — APPROVED** [review]

**Review by snsavage — APPROVED** [review]

**Review by wintondeshong — APPROVED** [review]

**Comment by wintondeshong** [comment]
Thanks @brandongregoryscott !

**Comment by brandongregoryscott** [comment]
@all-contributors add @jstevenson for review

**Comment by brandongregoryscott** [comment]
@all-contributors add @myty for review

**Comment by brandongregoryscott** [comment]
@all-contributors add @snsavage for review

**Comment by brandongregoryscott** [comment]
@all-contributors add @wintondeshong for review

**Pull request merged**
